orbs:
  qlty: qltysh/qlty-orb@0.0
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:24.14.0
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: install packages
          command: npm ci
      - run:
          name: build
          command: npm run build

      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test:ci
      - run:
          name: Run coverage
          command: npm run test:cov:ci
          when: always
      - qlty/coverage_publish:
          files: coverage/lcov.info
      - store_artifacts:
          path: ./coverage/lcov.info
          prefix: tests

workflows:
  orb-free-workflow:
    jobs:
      - test:
          context:
            - org-global
            - Trade-Automation-System
